version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/taskmanager
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build: ./frontend/client
    ports:
      - "3000:3000"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
