services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://meryamradouani_db_user:UK3pDTl80yolv2fY@cluster0.tsubttf.mongodb.net/TaskManager?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=meryam1234
      - ADMIN_EMAIL=meryam@admin.com
      - ADMIN_PASSWORD=meryam1234
      - CLIENT_URL=http://localhost:80
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/auth/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge