apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev  # ⬅️ AJOUTER ICI AUSSI
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http